# Data Pre-processing
- Data Type Correction
- Duplicate Handling
- Remove irrelevant columns
- Save cleaned data

In [11]:
# Imports
import pandas as pd
import numpy as np
import tensorflow as tf

In [12]:
# Load Data
DATA_PATH = r"C:\Users\hp\Downloads\BIA\Twitter_Sentiment_Analysis\Data\Twitter_Data.csv"
data= pd.read_csv(DATA_PATH)
data.head()

,textID,text,selected_text,sentiment
0,cb774db0d1,"I`d have responded, if I were going","I`d have responded, if I were going",neutral
1,549e992a42,Sooo SAD I will miss you here in San Diego!!!,Sooo SAD,negative
2,088c60f138,my boss is bullying me...,bullying me,negative
3,9642c003ef,what interview! leave me alone,leave me alone,negative
4,358bd9e861,"Sons of ****, why couldn`t they put them on t...","Sons of ****,",negative

In [13]:
# Data back-up
df = data.copy()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27481 entries, 0 to 27480
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   textID         27481 non-null  object
 1   text           27480 non-null  object
 2   selected_text  27480 non-null  object
 3   sentiment      27481 non-null  object
dtypes: object(4)
memory usage: 858.9+ KB

In [14]:
# Meta data
print("Number of rows: ",df.shape[0])
print("Number of columns:",df.shape[1])
all_columns= df.columns.to_list()
print("All columns: \n", all_columns)

Number of rows:  27481
Number of columns: 4
All columns:
 ['textID', 'text', 'selected_text', 'sentiment']

In [5]:
# Duplicates
print("Duplicate details: ", df.duplicated().sum())
print("Duplicated rows: \n")
df[df.duplicated()]

Duplicate details:  0
Duplicated rows:

Empty DataFrame
Columns: [textID, text, selected_text, sentiment]
Index: []

In [15]:
# Check null values
df.isnull().sum()

textID           0
text             1
selected_text    1
sentiment        0
dtype: int64

In [16]:
# Remove rows
df = df.dropna()
df.isnull().sum()

textID           0
text             0
selected_text    0
sentiment        0
dtype: int64

In [18]:
# Drop irrelevant column
df.drop(columns = ["textID","selected_text"],axis= 1, inplace= True)

In [19]:
df.head()

                                                text sentiment
0                I`d have responded, if I were going   neutral
1      Sooo SAD I will miss you here in San Diego!!!  negative
2                          my boss is bullying me...  negative
3                     what interview! leave me alone  negative
4   Sons of ****, why couldn`t they put them on t...  negative

In [20]:
# save cleaned data
CLEANED_DATA_PATH = r"C:\Users\hp\Downloads\BIA\Twitter_Sentiment_Analysis\Data\cleaned_data.csv"
df.to_csv(CLEANED_DATA_PATH, index= False)